# coding:utf-8

import os
import sys
import re
import json

"""
将swag init生成的docs/swagger.json的router路由信息生成为Go代码
以实现通过swagger注视自动注册router
"""

CODE_TEMPLATE = """// Code generated by meta_code; DO NOT EDIT.

func AutoRegistRouter( e *echo.Echo ) {
    
    g = e.Group({BASE_PATH})
        {ROUTERS}
    }

"""

doc_path = sys.argv[1] if len(sys.argv) > 1 else "docs/swagger.json"
print(doc_path)
with open(doc_path,encoding="utf-8") as f:
    doc_content = json.load(f)
base_path = doc_content.get("basePath","/")
print(base_path)
paths = doc_content.get("paths",[])
for path,path_content in paths.items():
    for method in path_content.keys():
        print(path.strip().strip("/"),method)
        
# print(paths)

